console.log("Hey Abu Hurairah, I have started learning TYPESCRIPT.");
var username = "Zoahib";
console.log(username);
var num1 = 10;
var num2 = 23;
var num3 = 21;
var num4 = 12;
var num5 = 9;
var num6 = 32;
var num7 = 12;
var num8 = 21;
var num9 = 32;
var num10 = 21;
var addition = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num8 + num9 + num10);
console.log(addition);
var subtraction = (num2 - num1);
console.log(subtraction);
var multiply = (num1 * num2);
console.log(multiply);
var division = (num6 / num1);
console.log(division);
